name: flutt_chat
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.10.16
  cupertino_icons: ^1.0.2
  tie_picker: ^0.0.2
  flutter_dotenv: ^5.1.0
  get_it: ^7.6.2
  logger: ^2.0.1
  image_picker: ^0.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_application_id: ^2.0.0-dev
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"

flutter_application_id:
  android:
    id: "dev.brihanpenayo.flutter_chat"
    name: "Flutt Chat"
  ios:
    id: "dev.brihanpenayo.flutter_chat"
    name: "Flutt Chat"
flutter:
  uses-material-design: true
  assets:
    - .env 
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Majes
      fonts:
        - asset: assets/fonts/Majes_icons.ttf